In [1]:
import openpyxl
import os
import pandas as pd
from openpyxl import load_workbook

In [5]:
daily_totals = pd.read_excel ('SALES LOG - XYZ COMPANY.xlsx')
daily_totals

,SALES ID,DEPOSIT DATE,TENDER TYPE,SALES TYPE,PO #,DATE OF SALE,TAX RCPT,SPECIAL,SALE AMT,TAX EXEMPT AMT,...,ATH CAP,ATH AC CU,ATH RESTRICTRED,RESTRICTED PD,CURRENT USE PD,ATH CU PD,ATH CAP PD,ATH CU PD.1,ATH RESTRICTED PD,ADJ
0,1,2020-02-26 00:00:00,CK,Check,81551,2020-03-02,19,1,1090.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2020-02-27 00:00:00,CK,Check,81563,2020-03-02,5,NaN,6578.84,1300,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2020-02-27 00:00:00,CK,Check,81564,2020-03-02,0,1,200.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2020-02-27 00:00:00,CK,Check,81565,2020-03-02,10,0,1700.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,2020-02-27 00:00:00,CK,Check,81566,2020-03-02,8,0,3675.00,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
168,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
171,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
172,NaN,NaN,NaN,NaN,NaN,2020-03-20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
pwd

'C:\\Users\\jmfon\\Documents\\Automation_Project\\First-automation-project'